title: Tools & Craft
description: Thoughts on industry developments, experiments, new tools, and tutorials
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Show post excerpts on the home page
show_excerpts: true

# Categories
categories: [industry-developments, experiments, tools, tutorials]

# Pagination
paginate: 6
paginate_path: "/page:num/"

# Excerpt separator
excerpt_separator: <!--more-->

# Exclude files from processing
exclude:
  - .specstory
  - .git
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock 