title: My Tech Blog
description: A blog about industry developments, experiments, new tools, and tutorials
baseurl: ""
url: ""

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag

# Categories
categories: [industry-developments, experiments, tools, tutorials]

# Pagination
paginate: 5
paginate_path: "/page:num/"

# Exclude files from processing
exclude:
  - .specstory
  - .git
  - .gitignore
  - README.md
  - Gemfile
  - Gemfile.lock 